In [2]:
import pandas as pd
data = pd.read_csv('stmf.csv', skiprows=2)

In [3]:
data.head()

,CountryCode,Year,Week,Sex,D0_14,D15_64,D65_74,D75_84,D85p,DTotal,R0_14,R15_64,R65_74,R75_84,R85p,RTotal,Split,SplitSex,Forecast
0,AUT,2000,1,m,7.0,183.0,212.0,249.0,163.0,814.0,0.000520,0.003513,0.037607,0.095138,0.231834,0.010925,0,0,0
1,AUT,2000,1,f,2.0,104.0,141.0,338.0,468.0,1053.0,0.000156,0.002002,0.019553,0.061442,0.224357,0.013238,0,0,0
2,AUT,2000,1,b,9.0,287.0,353.0,587.0,631.0,1867.0,0.000343,0.002759,0.027474,0.072305,0.226242,0.012120,0,0,0
3,AUT,2000,2,m,4.0,195.0,195.0,259.0,187.0,840.0,0.000297,0.003743,0.034591,0.098958,0.265969,0.011274,0,0,0
4,AUT,2000,2,f,6.0,109.0,126.0,312.0,509.0,1062.0,0.000469,0.002099,0.017473,0.056716,0.244012,0.013352,0,0,0

In [4]:
data.shape

(94629, 19)

In [20]:
data.info

<bound method DataFrame.info of       CountryCode  Year  Week Sex       D0_14        D15_64        D65_74  \
2             AUT  2000     1   b    9.000000    287.000000    353.000000
5             AUT  2000     2   b   10.000000    304.000000    321.000000
8             AUT  2000     3   b   13.000000    342.000000    346.000000
11            AUT  2000     4   b   24.000000    295.000000    342.000000
14            AUT  2000     5   b   16.000000    304.000000    314.000000
...           ...   ...   ...  ..         ...           ...           ...
94616         USA  2020    37   b  483.460096  14227.539904  10556.807247
94619         USA  2020    38   b  462.553713  13561.446287  10484.571538
94622         USA  2020    39   b  404.190062  13082.809938  10396.225706
94625         USA  2020    40   b  390.252474  11899.747526   9718.041524
94628         USA  2020    41   b  272.654072   9856.345928   8465.349594

             D75_84          D85p   DTotal     R0_14    R15_64    R65_74  \
2        587.000000    631.000000   1867.0  0.000343  0.002759  0.027474
5        571.000000    696.000000   1902.0  0.000381  0.002922  0.024983
8        573.000000    753.000000   2027.0  0.000495  0.003287  0.026929
11       571.000000    708.000000   1940.0  0.000914  0.002836  0.026618
14       563.000000    731.000000   1928.0  0.000609  0.002922  0.024439
...             ...           ...      ...       ...       ...       ...
94616  13084.577314  16986.615439  55339.0  0.000419  0.003474  0.016849
94619  12995.045157  16870.383306  54374.0  0.000400  0.003312  0.016734
94622  12885.545396  16728.228899  53497.0  0.000350  0.003195  0.016593
94625  12044.973701  15636.984774  49690.0  0.000338  0.002906  0.015511
94628  10492.331503  13621.318903  42708.0  0.000236  0.002407  0.013511

         R75_84      R85p    RTotal  Split  SplitSex  Forecast
2      0.072305  0.226242  0.012120      0         0         0
5      0.070334  0.249547  0.012347      0         0         0
8      0.070581  0.269984  0.013158      0         0         0
11     0.070334  0.253850  0.012593      0         0         0
14     0.069349  0.262096  0.012516      0         0         0
...         ...       ...       ...    ...       ...       ...
94616  0.041322  0.131957  0.008753      1         0         1
94619  0.041039  0.131054  0.008601      1         0         1
94622  0.040693  0.129949  0.008462      1         0         1
94625  0.038039  0.121472  0.007860      1         0         1
94628  0.033135  0.105814  0.006755      1         0         1

[31543 rows x 19 columns]>

# оставим катерогию "оба пола", чтобы не захламлять данные

In [6]:
data = data[data['Sex']=='b']
data.head()

,CountryCode,Year,Week,Sex,D0_14,D15_64,D65_74,D75_84,D85p,DTotal,R0_14,R15_64,R65_74,R75_84,R85p,RTotal,Split,SplitSex,Forecast
2,AUT,2000,1,b,9.0,287.0,353.0,587.0,631.0,1867.0,0.000343,0.002759,0.027474,0.072305,0.226242,0.012120,0,0,0
5,AUT,2000,2,b,10.0,304.0,321.0,571.0,696.0,1902.0,0.000381,0.002922,0.024983,0.070334,0.249547,0.012347,0,0,0
8,AUT,2000,3,b,13.0,342.0,346.0,573.0,753.0,2027.0,0.000495,0.003287,0.026929,0.070581,0.269984,0.013158,0,0,0
11,AUT,2000,4,b,24.0,295.0,342.0,571.0,708.0,1940.0,0.000914,0.002836,0.026618,0.070334,0.253850,0.012593,0,0,0
14,AUT,2000,5,b,16.0,304.0,314.0,563.0,731.0,1928.0,0.000609,0.002922,0.024439,0.069349,0.262096,0.012516,0,0,0

In [7]:
data['CountryCode'].unique()

array(['AUT', 'BEL', 'BGR', 'CAN', 'CHE', 'CHL', 'CZE', 'DEUTNP', 'DNK',
       'ESP', 'EST', 'FIN', 'FRATNP', 'GBRTENW', 'GBR_NIR', 'GBR_SCO',
       'GRC', 'HRV', 'HUN', 'ISL', 'ISR', 'ITA', 'KOR', 'LTU', 'LUX',
       'LVA', 'NLD', 'NOR', 'NZL_NP', 'POL', 'PRT', 'RUS', 'SVK', 'SVN',
       'SWE', 'USA'], dtype=object)

In [9]:
# You probably want to change just this number:
nWeekWindow = 26

# Possible age columns: 'D0_14', 'D15_64', 'D65_74','D75_84', 'D85p'
lstKeepAges = ['D0_14', 'D15_64', 'D65_74','D75_84', 'D85p']
# lstKeepAges = ['D65_74','D75_84', 'D85p']


#################################################################

# Probably stay the same

strURL_mortality = "https://www.mortality.org/Public/STMF/Outputs/stmf.csv"

lstCountriesEurope = ['AUT', 'BEL', 'BGR', 'CZE', 'DNK', 'GBRTENW', 'EST',
                      'FIN', 'FRATNP', 'DEUTNP', 'HUN', 'ISL', 'ITA', 
                      'LVA', 'LTU', 'LUX', 'NLD', 'NOR', 'POL', 'PRT',
                      'GBR_SCO', 'SVK', 'ESP', 'SWE', 'CHE']

nRefYearStart = 2015
nRefYearEnd = 2019 #inclusive

strSex = 'b'

#################################################################

# Don't touch these things
lstKeepCol = ['CountryCode', 'Year', 'Week', 'Sex'] + lstKeepAges

#  у каких стран нет всех данных?

In [11]:
lstFullCountryYearWeek = []
for strCountryCode in data['CountryCode'].unique():
    for nYear in range(nRefYearStart, nRefYearEnd+1):
        for nWeek in range(1,53):
            lstFullCountryYearWeek.append(strCountryCode + " " + str(nYear) + " " + str(nWeek))

print("No reference data for these country/year/week combos:")
set(lstFullCountryYearWeek)-set((data["CountryCode"] + " " + data["Year"].astype(str) + " " + data["Week"].astype(str)).values)

No reference data for these country/year/week combos:

{'CHL 2015 1',
 'CHL 2015 10',
 'CHL 2015 11',
 'CHL 2015 12',
 'CHL 2015 13',
 'CHL 2015 14',
 'CHL 2015 15',
 'CHL 2015 16',
 'CHL 2015 17',
 'CHL 2015 18',
 'CHL 2015 19',
 'CHL 2015 2',
 'CHL 2015 20',
 'CHL 2015 21',
 'CHL 2015 22',
 'CHL 2015 23',
 'CHL 2015 24',
 'CHL 2015 25',
 'CHL 2015 26',
 'CHL 2015 27',
 'CHL 2015 28',
 'CHL 2015 29',
 'CHL 2015 3',
 'CHL 2015 30',
 'CHL 2015 31',
 'CHL 2015 32',
 'CHL 2015 33',
 'CHL 2015 34',
 'CHL 2015 35',
 'CHL 2015 36',
 'CHL 2015 37',
 'CHL 2015 38',
 'CHL 2015 39',
 'CHL 2015 4',
 'CHL 2015 40',
 'CHL 2015 41',
 'CHL 2015 42',
 'CHL 2015 43',
 'CHL 2015 44',
 'CHL 2015 45',
 'CHL 2015 46',
 'CHL 2015 47',
 'CHL 2015 48',
 'CHL 2015 49',
 'CHL 2015 5',
 'CHL 2015 50',
 'CHL 2015 51',
 'CHL 2015 52',
 'CHL 2015 6',
 'CHL 2015 7',
 'CHL 2015 8',
 'CHL 2015 9',
 'DEUTNP 2015 1',
 'DEUTNP 2015 10',
 'DEUTNP 2015 11',
 'DEUTNP 2015 12',
 'DEUTNP 2015 13',
 'DEUTNP 2015 14',
 'DEUTNP 2015 15',
 'DEUTNP 2015 16',
 'DEUTNP 2015 17',
 'DEUTNP 2015 18',
 'DEUTNP 2015 19',
 'DEUTNP 2015 2',
 'DEUTNP 2015 20',
 'DEUTNP 2015 21',
 'DEUTNP 2015 22',
 'DEUTNP 2015 23',
 'DEUTNP 2015 24',
 'DEUTNP 2015 25',
 'DEUTNP 2015 26',
 'DEUTNP 2015 27',
 'DEUTNP 2015 28',
 'DEUTNP 2015 29',
 'DEUTNP 2015 3',
 'DEUTNP 2015 30',
 'DEUTNP 2015 31',
 'DEUTNP 2015 32',
 'DEUTNP 2015 33',
 'DEUTNP 2015 34',
 'DEUTNP 2015 35',
 'DEUTNP 2015 36',
 'DEUTNP 2015 37',
 'DEUTNP 2015 38',
 'DEUTNP 2015 39',
 'DEUTNP 2015 4',
 'DEUTNP 2015 40',
 'DEUTNP 2015 41',
 'DEUTNP 2015 42',
 'DEUTNP 2015 43',
 'DEUTNP 2015 44',
 'DEUTNP 2015 45',
 'DEUTNP 2015 46',
 'DEUTNP 2015 47',
 'DEUTNP 2015 48',
 'DEUTNP 2015 49',
 'DEUTNP 2015 5',
 'DEUTNP 2015 50',
 'DEUTNP 2015 51',
 'DEUTNP 2015 52',
 'DEUTNP 2015 6',
 'DEUTNP 2015 7',
 'DEUTNP 2015 8',
 'DEUTNP 2015 9',
 'GBR_NIR 2015 1',
 'GRC 2015 1',
 'GRC 2015 10',
 'GRC 2015 11',
 'GRC 2015 12',
 'GRC 2015 13',
 'GRC 2015 14',
 'GRC 2015 15',
 'GRC 2015 16',
 'GRC 2015 17',
 'GRC 2015 18',
 'GRC 2015 19',
 'GRC 2015 2',
 'GRC 2015 20',
 'GRC 2015 21',
 'GRC 2015 22',
 'GRC 2015 23',
 'GRC 2015 24',
 'GRC 2015 25',
 'GRC 2015 26',
 'GRC 2015 27',
 'GRC 2015 28',
 'GRC 2015 29',
 'GRC 2015 3',
 'GRC 2015 30',
 'GRC 2015 31',
 'GRC 2015 32',
 'GRC 2015 33',
 'GRC 2015 34',
 'GRC 2015 35',
 'GRC 2015 36',
 'GRC 2015 37',
 'GRC 2015 38',
 'GRC 2015 39',
 'GRC 2015 4',
 'GRC 2015 40',
 'GRC 2015 41',
 'GRC 2015 42',
 'GRC 2015 43',
 'GRC 2015 44',
 'GRC 2015 45',
 'GRC 2015 46',
 'GRC 2015 47',
 'GRC 2015 48',
 'GRC 2015 49',
 'GRC 2015 5',
 'GRC 2015 50',
 'GRC 2015 51',
 'GRC 2015 52',
 'GRC 2015 6',
 'GRC 2015 7',
 'GRC 2015 8',
 'GRC 2015 9',
 'ITA 2015 1'}

# максимальное число недель, доступное для каждой страны в 2020 году

In [12]:
data[['CountryCode']].\
      drop_duplicates().\
      merge(data[(data['Year']==2020)].\
                  sort_values(by=['CountryCode','Week']).\
                  drop_duplicates(subset=['CountryCode'], keep='last')[['CountryCode','Week']],
            on='CountryCode', how='left').\
      fillna(0).\
      sort_values(by='Week').\
      set_index(keys='CountryCode')

             Week
CountryCode
RUS           0.0
GRC          30.0
CAN          34.0
HRV          35.0
SVN          35.0
SVK          35.0
CZE          35.0
ITA          35.0
LUX          35.0
KOR          36.0
FRATNP       38.0
HUN          39.0
DEUTNP       39.0
POL          40.0
ISL          41.0
ISR          41.0
PRT          41.0
LTU          41.0
NZL_NP       41.0
USA          41.0
GBR_SCO      41.0
ESP          41.0
BEL          41.0
GBR_NIR      42.0
GBRTENW      42.0
FIN          42.0
NOR          42.0
CHL          42.0
CHE          42.0
BGR          42.0
SWE          42.0
AUT          42.0
EST          43.0
LVA          43.0
NLD          43.0
DNK          43.0

# Сделаем дата фрейм смертности за 2020

In [13]:
df_mortality_2020 = data[(data['Year']==2020)][lstKeepCol].sort_values(by=['CountryCode','Year','Week'])
df_mortality_2020['SUM'] = df_mortality_2020[lstKeepAges].sum(axis='columns')

df_mortality_2020.head(5)

     CountryCode  Year  Week Sex  D0_14  D15_64  D65_74  D75_84   D85p     SUM
3122         AUT  2020     1   b    1.0   220.0   221.0   482.0  687.0  1611.0
3125         AUT  2020     2   b    8.0   231.0   261.0   490.0  712.0  1702.0
3128         AUT  2020     3   b   12.0   223.0   272.0   537.0  753.0  1797.0
3131         AUT  2020     4   b   13.0   259.0   256.0   515.0  736.0  1779.0
3134         AUT  2020     5   b    9.0   226.0   277.0   591.0  844.0  1947.0

In [14]:
df_mortality_reference = data[(data['Year']>=nRefYearStart) &\
                                       (data['Year']<(nRefYearEnd+1))]
for strCol in lstKeepAges:
    df_mortality_reference = df_mortality_reference.\
                                merge(pd.DataFrame(df_mortality_reference[['CountryCode', 'Year', 'Week']+[strCol]].groupby(by=['CountryCode','Week'])[strCol].mean()).\
                                              reset_index().\
                                              rename(columns={strCol:strCol+'_REF'}),
                                     on=['CountryCode','Week'], how='outer')

df_mortality_reference['SUM'] = df_mortality_reference[lstKeepAges].sum(axis='columns')

df_mortality_reference = df_mortality_reference.\
                                merge(pd.DataFrame(df_mortality_reference[lstKeepCol+['SUM']].groupby(by=['CountryCode','Week'])['SUM'].mean()).\
                                          reset_index().\
                                          rename(columns={'SUM':'REF_SUM'}),
                                      on=['CountryCode','Week'], how='outer')
df_mortality_reference = df_mortality_reference[['CountryCode','Week']+[x+'_REF' for x in lstKeepAges]+['REF_SUM']].\
                              drop_duplicates().\
                              round(2).\
                              reset_index(drop=True).\
                              sort_values(by=['CountryCode','Week'])

df_mortality_reference.head(5)

,CountryCode,Week,D0_14_REF,D15_64_REF,D65_74_REF,D75_84_REF,D85p_REF,REF_SUM
0,AUT,1,6.2,232.6,287.8,509.0,773.4,1809.0
1,AUT,2,7.0,234.4,276.0,517.4,822.2,1857.0
2,AUT,3,6.0,240.6,275.0,489.2,775.6,1786.4
3,AUT,4,8.2,226.8,269.8,467.4,774.8,1747.0
4,AUT,5,10.4,240.2,277.6,492.6,797.8,1818.6

In [15]:
df_mortality_join = df_mortality_2020[lstKeepCol+['SUM']].merge(df_mortality_reference, on=['CountryCode','Week'])
df_mortality_join['DIFF'] = df_mortality_join['SUM']-df_mortality_join['REF_SUM']
df_mortality_join['EXCESS_ONLY'] = df_mortality_join['DIFF'].clip(0, None)

df_mortality_join.head(5)

,CountryCode,Year,Week,Sex,D0_14,D15_64,D65_74,D75_84,D85p,SUM,D0_14_REF,D15_64_REF,D65_74_REF,D75_84_REF,D85p_REF,REF_SUM,DIFF,EXCESS_ONLY
0,AUT,2020,1,b,1.0,220.0,221.0,482.0,687.0,1611.0,6.2,232.6,287.8,509.0,773.4,1809.0,-198.0,0.0
1,AUT,2020,2,b,8.0,231.0,261.0,490.0,712.0,1702.0,7.0,234.4,276.0,517.4,822.2,1857.0,-155.0,0.0
2,AUT,2020,3,b,12.0,223.0,272.0,537.0,753.0,1797.0,6.0,240.6,275.0,489.2,775.6,1786.4,10.6,10.6
3,AUT,2020,4,b,13.0,259.0,256.0,515.0,736.0,1779.0,8.2,226.8,269.8,467.4,774.8,1747.0,32.0,32.0
4,AUT,2020,5,b,9.0,226.0,277.0,591.0,844.0,1947.0,10.4,240.2,277.6,492.6,797.8,1818.6,128.4,128.4

In [16]:
df_excess_mortality = pd.DataFrame(df_mortality_join[df_mortality_join['Week']<=nWeekWindow].groupby(by=['CountryCode'])[['REF_SUM','EXCESS_ONLY']].sum()).reset_index()

df_excess_mortality['%_INCREASE'] = df_excess_mortality['EXCESS_ONLY']*100.0/df_excess_mortality['REF_SUM']

# Tacking on the LAST_INCLUDED_WEEK column
df_excess_mortality = df_excess_mortality.merge(df_mortality_join[df_mortality_join['Week']<=nWeekWindow].\
                                                      drop_duplicates(subset=['CountryCode'], keep='last')[['CountryCode','Week']].\
                                                      rename(columns={'Week':'LAST_INCLUDED_WEEK'}),
                                                on='CountryCode', how='left')

df_excess_mortality.set_index(keys='CountryCode').round(2)

                REF_SUM  EXCESS_ONLY  %_INCREASE  LAST_INCLUDED_WEEK
CountryCode
AUT            42005.40      1641.40        3.91                  26
BEL            57350.00      8960.80       15.62                  26
BGR            56651.40       150.40        0.27                  26
CAN           141123.00      9532.00        6.75                  26
CHE            34447.40      2024.80        5.88                  26
CHL            51735.50     10440.50       20.18                  26
CZE            57361.80       955.00        1.66                  26
DEUTNP        483863.25     12446.75        2.57                  26
DNK            27704.60       539.20        1.95                  26
ESP           220613.00     48854.60       22.14                  26
EST             8029.80       221.40        2.76                  26
FIN            27517.40       984.20        3.58                  26
FRATNP        304732.20     30242.40        9.92                  26
GBRTENW       281501.00     59657.60       21.19                  26
GBR_NIR         8273.60      1073.80       12.98                  26
GBR_SCO        30068.00      5005.80       16.65                  26
GRC            63066.50      2267.00        3.59                  26
HRV            27479.00       186.00        0.68                  26
HUN            67819.80       625.40        0.92                  26
ISL             1151.40        84.80        7.36                  26
ISR            23254.00      1078.20        4.64                  26
ITA           313998.65     63158.80       20.11                  26
KOR           145829.20      6121.80        4.20                  26
LTU            21068.80       318.00        1.51                  26
LUX             2134.60       158.40        7.42                  26
LVA            14842.80       164.00        1.10                  26
NLD            78152.80     10019.00       12.82                  26
NOR            20982.80       283.60        1.35                  26
NZL_NP         15738.80       590.60        3.75                  26
POL           207707.80      4359.00        2.10                  26
PRT            58786.80      3893.60        6.62                  26
SVK            27684.20       268.60        0.97                  26
SVN            10540.80       387.60        3.68                  26
SWE            46053.00      5668.40       12.31                  26
USA          1426784.80    199559.40       13.99                  26

In [17]:
print("Europe:")
s_temp = df_excess_mortality[df_excess_mortality['CountryCode'].isin(lstCountriesEurope)][['REF_SUM','EXCESS_ONLY']].sum()
print("\tReference deaths:", int(s_temp['REF_SUM']))
print("\tExcess deaths:", int(s_temp['EXCESS_ONLY']))
print("\tPercent increase:", round(s_temp['EXCESS_ONLY']*100.0/s_temp['REF_SUM'], 2))

print()

print("United States:")
s_temp = df_excess_mortality[df_excess_mortality['CountryCode'].isin(['USA'])][['REF_SUM','EXCESS_ONLY']].sum()
print("\tReference deaths:", int(s_temp['REF_SUM']))
print("\tExcess deaths:", int(s_temp['EXCESS_ONLY']))
print("\tPercent increase:", round(s_temp['EXCESS_ONLY']*100.0/s_temp['REF_SUM'], 2))

Europe:
	Reference deaths: 2492228
	Excess deaths: 260685
	Percent increase: 10.46

United States:
	Reference deaths: 1426784
	Excess deaths: 199559
	Percent increase: 13.99

In [18]:
# Run this as a reminder of what your variables were
print(lstKeepAges)
print(nWeekWindow)

['D0_14', 'D15_64', 'D65_74', 'D75_84', 'D85p']
26

In [19]:
print("Up to week", nWeekWindow)
df_mortality_join[df_mortality_join['CountryCode']=='USA']

Up to week 26

,CountryCode,Year,Week,Sex,D0_14,D15_64,D65_74,D75_84,D85p,SUM,D0_14_REF,D15_64_REF,D65_74_REF,D75_84_REF,D85p_REF,REF_SUM,DIFF,EXCESS_ONLY
1344,USA,2020,1,b,575.796619,14773.203381,11596.949499,14373.775970,18660.274531,59980.0,611.61,14575.59,11411.37,14281.01,18980.01,59859.6,120.4,120.4
1345,USA,2020,2,b,567.085626,14542.914374,11790.011126,14613.065153,18970.923720,60484.0,592.78,14467.22,11686.11,14626.96,19440.33,60813.4,-329.4,0.0
1346,USA,2020,3,b,593.218604,14294.781396,11477.682626,14225.951293,18468.366081,59060.0,599.98,14110.82,11486.20,14377.90,19110.90,59685.8,-625.8,0.0
1347,USA,2020,4,b,578.409916,14163.590084,11417.139747,14150.911751,18370.948503,58681.0,593.30,13919.10,11254.31,14085.52,18722.97,58575.2,105.8,105.8
1348,USA,2020,5,b,567.085626,14070.914374,11390.635997,14118.061822,18328.302180,58475.0,606.53,13885.27,11096.64,13887.29,18460.07,57935.8,539.2,539.2
1349,USA,2020,6,b,612.382788,14457.617212,11464.950433,14210.170445,18447.879123,59193.0,608.44,14153.76,11096.45,13886.09,18457.86,58202.6,990.4,990.4
1350,USA,2020,7,b,578.409916,14186.590084,11396.092652,14124.825043,18337.082306,58623.0,625.94,13889.86,11023.47,13794.34,18337.59,57671.2,951.8,951.8
1351,USA,2020,8,b,555.761335,14202.238665,11398.431218,14127.723566,18340.845216,58625.0,603.08,13794.92,10888.10,13625.59,18115.11,57026.8,1598.2,1598.2
1352,USA,2020,9,b,607.156192,14406.843808,11447.541107,14188.592551,18419.866343,59070.0,617.47,13922.93,10761.66,13467.97,17907.36,56677.4,2392.6,2392.6
1353,USA,2020,10,b,515.690769,14592.309231,11518.997294,14277.158534,18534.844172,59439.0,600.43,14075.97,10804.46,13520.34,17975.80,56977.0,2462.0,2462.0
1354,USA,2020,11,b,548.792541,14212.207459,11351.400054,14069.431046,18265.168900,58447.0,599.21,13905.59,10627.94,13300.18,17682.28,56115.2,2331.8,2331.8
1355,USA,2020,12,b,565.343427,14414.656573,11438.706524,14177.642574,18405.650902,59002.0,634.30,13693.30,10583.20,13242.44,17605.96,55759.2,3242.8,3242.8
1356,USA,2020,13,b,518.304067,15239.695933,12212.512076,15136.731657,19650.756267,62758.0,607.79,13491.01,10416.36,13033.98,17328.26,54877.4,7880.6,7880.6
1357,USA,2020,14,b,498.268783,17527.731217,14025.680358,17384.053221,22568.266421,72004.0,595.08,13727.32,10344.16,12943.60,17207.65,54817.8,17186.2,17186.2
1358,USA,2020,15,b,547.921442,18639.078558,15486.504675,19194.663973,24918.831351,78787.0,597.30,13570.30,10263.59,12842.43,17072.77,54346.4,24440.6,24440.6
1359,USA,2020,16,b,483.460096,17568.539904,15185.349324,18821.398612,24434.252064,76493.0,607.80,13354.60,10099.99,12639.68,16804.93,53507.0,22986.0,22986.0
1360,USA,2020,17,b,544.437045,17331.562955,14469.228403,17933.806432,23281.965165,73561.0,607.66,13124.74,9942.39,12441.36,16539.25,52655.4,20905.6,20905.6
1361,USA,2020,18,b,513.077471,16553.922529,13486.770783,16716.104679,21701.124538,68971.0,612.87,13340.53,9875.72,12358.32,16429.17,52616.6,16354.4,16354.4
1362,USA,2020,19,b,560.987931,16763.012069,12800.271700,15865.227125,20596.501175,66586.0,606.71,13378.29,9718.20,12162.36,16171.03,52036.6,14549.4,14549.4
1363,USA,2020,20,b,576.667718,16120.332282,12358.802380,15318.050379,19886.147241,64260.0,612.17,13228.43,9632.66,12053.93,16026.61,51553.8,12706.2,12706.2
1364,USA,2020,21,b,587.120909,15970.879091,11641.122415,14428.525850,18731.351735,61359.0,613.06,13057.74,9554.26,11955.01,15893.72,51073.8,10285.2,10285.2
1365,USA,2020,22,b,544.437045,15501.562955,11266.432151,13964.118041,18128.449808,59405.0,632.12,13261.88,9447.68,11822.79,15718.33,50882.8,8522.2,8522.2
1366,USA,2020,23,b,605.413994,15927.586006,10932.017193,13549.629240,17590.353567,58605.0,627.98,13390.62,9471.91,11851.36,15754.73,51096.6,7508.4,7508.4
1367,USA,2020,24,b,588.863108,15581.136892,10797.679560,13383.125192,17374.195248,57725.0,638.28,13250.32,9451.22,11826.83,15722.95,50889.6,6835.4,6835.4
1368,USA,2020,25,b,584.507611,15530.492389,10797.419719,13382.803133,17373.777147,57669.0,643.02,13280.78,9380.17,11736.85,15602.98,50643.8,7025.2,7025.2
1369,USA,2020,26,b,539.210449,15639.789551,10899.796948,13509.694033,17538.509019,58127.0,615.74,13245.26,9356.10,11707.12,15563.78,50488.0,7639.0,7639.0
1370,USA,2020,27,b,607.156192,16253.843808,11052.583269,13699.064208,17784.352523,59397.0,620.36,13558.44,9347.60,11696.79,15549.61,50772.8,8624.2,8624.2
1371,USA,2020,28,b,614.996086,16860.003914,11416.879906,14150.589692,18370.530401,61413.0,612.46,13306.34,9299.05,11635.87,15468.68,50322.4,11090.6,11090.6
1372,USA,2020,29,b,541.823747,16810.176253,11752.334227,14566.366726,18910.299047,62581.0,613.17,13204.63,9283.88,11617.92,15445.80,50165.4,12415.6,12415.6
1373,USA,2020,30,b,578.409916,16880.590084,12001.781282,14875.542521,19311.676196,63648.0,620.00,13118.20,9235.23,11556.54,15364.24,49894.2,13753.8,13753.8
1374,USA,2020,31,b,513.948570,16777.051430,12010.615866,14886.492497,19325.891637,63514.0,588.15,13215.05,9237.96,11558.76,15366.28,49966.2,13547.8,13547.8
1375,USA,2020,32,b,559.245732,16608.754268,11838.341493,14672.967964,19048.690543,62728.0,609.95,13338.65,9226.10,11542.83,15344.47,50062.0,12666.0,12666.0
1376,USA,2020,33,b,505.237578,16221.762422,11824.569937,14655.898883,19026.531180,62234.0,604.35,13008.85,9254.07,11578.28,15392.65,49838.2,12395.8,12395.8
1377,USA,2020,34,b,486.944493,15536.055507,11567.067821,14336.739286,18612.192893,60539.0,616.19,13032.41,9227.75,11546.50,15350.15,49773.0,10766.0,10766.0
1378,USA,2020,35,b,506.979776,14916.020224,11089.740487,13745.118519,17844.140994,58102.0,576.61,13080.79,9313.99,11653.69,15492.92,50118.0,7984.0,7984.0
1379,USA,2020,36,b,475.620202,14668.379798,10766.758519,13344.800275,17324.441206,56580.0,593.38,13387.82,9293.68,11628.42,15460.10,50363.4,6216.6,6216.6
1380,USA,2020,37,b,483.460096,14227.539904,10556.807247,13084.577314,16986.615439,55339.0,609.60,13079.80,9428.40,11796.38,15682.83,50597.0,4742.0,4742.0
1381,USA,2020,38,b,462.553713,13561.446287,10484.571538,12995.045157,16870.383306,54374.0,603.19,13060.01,9446.12,11818.92,15711.96,50640.2,3733.8,3733.8
1382,USA,2020,39,b,404.190062,13082.809938,10396.225706,12885.545396,16728.228899,53497.0,600.83,13050.57,9512.24,11901.90,15822.46,50888.0,2609.0,2609.0
1383,USA,2020,40,b,390.252474,11899.747526,9718.041524,12044.973701,15636.984774,49690.0,583.95,13327.65,9588.33,11995.66,15946.21,51441.8,-1751.8,0.0
1384,USA,2020,41,b,272.654072,9856.345928,8465.349594,10492.331503,13621.318903,42708.0,580.45,13277.15,9720.57,12163.87,16172.77,51914.8,-9206.8,0.0